name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test-sh:
    name: tests under dash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run tests under dash
        run: dash tests/test-gw.sh
